version: "3.11"

services:

    backend:
      build:
        context: .
      env_file:
        - .env.prod
      container_name: backend
      restart: on-failure
      expose:
        - 8000
      ports:
        - 8000:8000
      command: [ "/docker/api.sh" ]
      depends_on:
        postgres:
          condition: service_healthy

    postgres:
      image: postgres:15.1-alpine
      env_file:
        - .env.prod
      container_name: postgres
      restart: always
      command: -p 5432
      expose:
        - 5432
      ports:
        - 5432:5432
      volumes:
        - postgres_db:/var/lib/postgresql/data
      healthcheck:
        test: [ "CMD-SHELL", "pg_isready", "-U", "postgres" ]
        interval: 5s
        timeout: 5s
        retries: 5

volumes:
  postgres_db: