"""Создание таблиц

Revision ID: 22231b50cc23
Revises: a50f730c3d5d
Create Date: 2024-07-14 14:24:39.646278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22231b50cc23'
down_revision: Union[str, None] = 'a50f730c3d5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=1024),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=sa.String(length=1024),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
