"""Изменение поля URL изображения к категориям

Revision ID: b64ae2db7656
Revises: e786629a167c
Create Date: 2024-06-23 19:03:23.962139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b64ae2db7656'
down_revision: Union[str, None] = 'e786629a167c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('image', sa.String(length=300), nullable=True))
    op.drop_column('category', 'url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('url', sa.VARCHAR(length=300), autoincrement=False, nullable=True))
    op.drop_column('category', 'image')
    # ### end Alembic commands ###
