"""Добавление URL изображения к категориям

Revision ID: e786629a167c
Revises: e0e064a3c252
Create Date: 2024-06-23 19:00:29.586361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e786629a167c'
down_revision: Union[str, None] = 'e0e064a3c252'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('url', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'url')
    # ### end Alembic commands ###
